### ISSUE TITLE
[bug] Wide `Secret` access for "kcm-namespace-viewer-role" `ClusterRole`

### ISSUE THREAD

**Issue by s3rj1k** [k0rdent/kcm#1033]
**Describe the bug:**
Wide `Secret` access for "kcm-namespace-viewer-role" `ClusterRole`, user with this `ClusterRole` can lookup `Secret` from all namespaces

**To Reproduce:**
1. Spin-up `k0rdent` cluster
2. Generate certs
```
openssl genrsa -out user.key 2048
openssl req -new -key user.key -out user.csr -subj "/CN=user/O=namespace-viewer"
```
3. Create CSR
```
kubectl apply -f - <<EOF
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user-csr
spec:
  request: $(cat user.csr | base64 | tr -d "\n")
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
EOF
```
4. Get Certificate
```
kubectl certificate approve user-csr
kubectl get csr user-csr -o jsonpath='{.status.certificate}' | base64 -d > user.crt
```
5. Create RoleBinding
```
kubectl apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-viewer
subjects:
  - kind: User
    name: user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcm-namespace-viewer-role
EOF
```
6. Configure and save kubeconfig
```
ORIGINAL_CONTEXT=$(kubectl config current-context)
kubectl config set-credentials user --client-key=user.key --client-certificate=user.crt --embed-certs=true
kubectl config set-context user-context --cluster=$(kubectl config current-context | cut -d@ -f2) --user=user --namespace=kcm-system
kubectl config use-context user-context
kubectl config view --flatten > ns-viewer.kubeconfig
kubectl config use-context $ORIGINAL_CONTEXT
kubectl config view --kubeconfig ns-viewer.kubeconfig
```

**Expected behavior**
```
# kubectl --kubeconfig ns-viewer.kubeconfig auth can-i get secrets -n kcm-system
yes
# kubectl --kubeconfig ns-viewer.kubeconfig auth can-i get secrets --all-namespaces
no
```

**Actual behavior**
```
# kubectl --kubeconfig ns-viewer.kubeconfig auth can-i get secrets -n kcm-system
yes
# kubectl --kubeconfig ns-viewer.kubeconfig auth can-i get secrets --all-namespaces
yes
```

**Additional context**
Above used `ClusterRole` does not have access to `Pod`s, so we can verify kubconfig like so:
```
# kubectl --kubeconfig ns-viewer.kubeconfig auth can-i get pods -n kcm-system
no
# kubectl --kubeconfig ns-viewer.kubeconfig auth can-i get pods --all-namespaces
no
```

**Comment by Kshatrix** [comment]
please use rolebinding instead of clusterrolebinding if you want it to be limited to some specific namespace

**Comment by s3rj1k** [comment]
for reference
```
kubectl apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-viewer
  namespace: kcm-system
subjects:
  - kind: User
    name: user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcm-namespace-viewer-role
EOF
```
will restrict to `kcm-system`
