### ISSUE TITLE
[enhancement] add capability to deploy services using sources other than HelmChart

### ISSUE THREAD

**Issue by BROngineer** [k0rdent/kcm#1043]
thread: https://miracloud.slack.com/archives/C075Z4V0TA5/p1738743515927559

tl;dr kcm does not support deploying services from git repositories

**Comment by s3rj1k** [comment]
Below **does not** work:
```
cat <<'EOF' | kubectl apply -f -
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-community
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/managed: "true"
spec:
  interval: 10m0s
  url: https://github.com/prometheus-community/helm-charts.git
  ref:
    tag: prometheus-25.8.2
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: prometheus-25-8-2
  namespace: kcm-system
spec:
  helm:
    chartSpec:
      chart: ./charts/prometheus
      version: 25.8.2
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: prometheus-community
EOF

kubectl patch clusterdeployment -n kcm-system openstack --type=merge --patch "$(cat <<'EOF'
spec:
  serviceSpec:
    services:
      - template: prometheus-25-8-2
        name: prometheus
        namespace: prometheus
EOF
)"

kubectl get secret -n kcm-system openstack-kubeconfig -o=jsonpath={.data.value} | base64 -d > openstack.kubeconfig

kubectl --kubeconfig openstack.kubeconfig get pods -n prometheus
```

**Comment by BROngineer** [comment]
@s3rj1k sveltos currently does not support helm chart installation from git repo, unforunately

**Comment by s3rj1k** [comment]
How is Sveltos related to this? Charts are handled by Flux components last time I've cheked

**Comment by BROngineer** [comment]
In general - yes. However we create sveltos CRs - Profile/ClusterProfile out of our ServiceTemplates. Sveltos CRs has three fields related to artifacts to be deployed:
- helmCharts
- policyRefs
- kustomizationRefs

helmRefs in turn contains the list of structs where the following fields specified:
```yaml
helmCharts:
  - repositoryURL:    https://kyverno.github.io/kyverno/
    repositoryName:   kyverno
    chartName:        kyverno/kyverno
    chartVersion:     v3.3.3
    releaseName:      kyverno-latest
    releaseNamespace: kyverno
    helmChartAction:  Install
```
Sveltos **expects valid helm repository** as a source.

REF to conversation with maintainer: https://projectsveltos.slack.com/archives/C046L9HFJFP/p1741251089509189
