### ISSUE TITLE
[e2e] The resource-template ConfigMap is missing

### ISSUE THREAD

**Issue by eromanova** [k0rdent/kcm#1087]
Currently, the e2e tests are not aligned with the recent changes in pluggable providers. In e2e tests, all Credentials are created differently, leading to missing `resource-template` ConfigMap and the following condition in the cluster deployment:

```
    services:
    - clusterName: e2e-test-cbcda233-aws-0
      clusterNamespace: kcm-system
      conditions:
      - lastTransitionTime: "2025-02-17T13:06:00Z"
        message: 'Referenced resource: ConfigMap kcm-system/infrastructure-aws-cluster-identity-resource-template
          does not exist'
        reason: FailedNonRetriable
        status: "False"
        type: Resources
```
