### ISSUE TITLE
[bug] KCM Silently Accepts ClusterDeployment Values That Make No Effect

### ISSUE THREAD

**Issue by aglarendil** [k0rdent/kcm#1216]
**Describe the bug**
Invalid (semantically) cluster deployment yamlconfig does not lead to its rejection, rather KCM accepts it and does nothing as the config is invalid.

**To Reproduce**
Make a usual "2 spaces" yaml typo and put servicesSpec a level deeper.
like this:

```
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: vsurzhyk-aws-managed-kind-1
  namespace: kcm-system
spec:
  template: aws-standalone-cp-0-1-0 # The name of the template you want to use from above
  credential: aws-cluster-identity-cred
  config:
    #controlPlaneNumber: 1
    #workersNumber: 1
    region: eu-west-1
    # US regions are cheepier
    #region: us-east-2
    controlPlane:
      instanceType: t3.medium
    worker:
      instanceType: t3.medium
      #instanceType: m5.xlarge
    serviceSpec: # <== should be a level higher
      services:
        - template: ingress-nginx-4-11-3
          name: ingress-nginx
          namespace: ingress-nginx
        - template: dex-0-19-1
          name: dex
          namespace: dex
      priority: 100
```
**Expected behavior**
The ServicesSpec above is EITHER deployed OR rejected by API. There are no values in the downstream child cluster template to consume this serviceSpec, it is obviously a typo. However, a user gets a silent OK from the API and no indication that the config is invalid.
