### ISSUE TITLE
[bug] Incorrect status of deployed services in ClusterDeployment

### ISSUE THREAD

**Issue by eromanova** [k0rdent/kcm#1295]
**Describe the bug**
The status of deployed services is calculated incorrectly for ClusterDeployment. I created an adopted cluster, added two services to the `spec.serviceSpec`. Services were deployed successfully but the status is incorrectly reported. In `status.services`:
```
  services:
  - clusterName: adopted-dev
    clusterNamespace: kcm-system
    conditions:
    - lastTransitionTime: "2025-03-27T17:19:20Z"
      message: ""
      reason: Provisioned
      status: "True"
      type: Resources
    - lastTransitionTime: "2025-03-27T17:19:20Z"
      message: ""
      reason: Provisioned
      status: "True"
      type: Helm
    - lastTransitionTime: "2025-03-27T17:19:20Z"
      message: Release kyverno/kyverno
      reason: Managing
      status: "True"
      type: kyverno.kyverno/SveltosHelmReleaseReady
    - lastTransitionTime: "2025-03-27T17:19:20Z"
      message: Release ingress-nginx/ingress-nginx
      reason: Managing
      status: "True"
      type: ingress-nginx.ingress-nginx/SveltosHelmReleaseReady
```

While in `status.conditions`:
```
  - lastTransitionTime: "2025-03-27T17:09:20Z"
    message: 1/2 Services are ready
    reason: Failed
    status: "False"
    type: Ready
```

The number of ready services is incorrectly calculated in `getServicesReadinessCondition`: https://github.com/k0rdent/kcm/blob/main/internal/controller/multiclusterservice_controller.go#L270

**To Reproduce**
1. Deploy any standalone or adopted cluster and add >2 services in `spec.serviceSpec`.  

**Expected behavior**
Ready services' status is reported properly.
