### ISSUE TITLE
[bug] deletion of services from a CLD spec does not delete resources

### ISSUE THREAD

**Issue by zerospiel** [k0rdent/kcm#1312]
1. Deploy a `cld` with the 

   ```yaml
     serviceSpec:
       services:
         - template: kyverno-3-2-6
           name: kyverno
           namespace: kyverno
         - template: ingress-nginx-4-11-0
           name: ingress-nginx
           namespace: ingress-nginx
   ```

1. Wait for the readiness

   ```yaml
     services:
     - clusterName: adopted-dev
       clusterNamespace: kcm-system
       conditions:
       - lastTransitionTime: "2025-03-27T17:19:20Z"
         message: ""
         reason: Provisioned
         status: "True"
         type: Resources
       - lastTransitionTime: "2025-03-27T17:19:20Z"
         message: ""
         reason: Provisioned
         status: "True"
         type: Helm
       - lastTransitionTime: "2025-03-27T17:19:20Z"
         message: Release kyverno/kyverno
         reason: Managing
         status: "True"
         type: kyverno.kyverno/SveltosHelmReleaseReady
       - lastTransitionTime: "2025-03-27T17:19:20Z"
         message: Release ingress-nginx/ingress-nginx
         reason: Managing
         status: "True"
         type: ingress-nginx.ingress-nginx/SveltosHelmReleaseReady
   ```
1. Remove any or all of the services from the `serviceSpec`
1. Wait for statuses updates reporting the service(s) is(are) gone now
1. Return the service(s) back
1. The `status` gets updated immediately reporting everything deployed

Such fast updates suggest that the services are not actually deleted from the cloud but rather just from the `cld` spec/status.

If that is the desired behavior, close the issue
