### ISSUE TITLE
[bug] openstack-standalone-cp templates - can't clean up resources on clusterdeployment deletion

### ISSUE THREAD

**Issue by ironreality** [k0rdent/kcm#1387]
**Describe the bug**
While trying to delete an Openstack clusterdeployment with a beach head service with LoadBalancer service attached - kcm can't clean up the related Openstack's load balancer, interface and router so clusterdeployment hangs in 'Ready' status despite its nodes have been already deleted.

```
# kubectl get clusterdeployment
NAME                                       READY   SERVICES   TEMPLATE                        MESSAGES          AGE
vsurzhyk-eu-openstack-cluster-deployment   True    3/3        openstack-standalone-cp-0-2-0   Object is ready   77m

# kubectl delete clusterdeployment vsurzhyk-eu-openstack-cluster-deployment
clusterdeployment.k0rdent.mirantis.com "vsurzhyk-eu-openstack-cluster-deployment" deleted
^C

# kubectl get clusterdeployment
kubectl get clusterdeployment
NAME                                       READY   SERVICES   TEMPLATE                        MESSAGES          AGE
vsurzhyk-eu-openstack-cluster-deployment   True    3/3        openstack-standalone-cp-0-2-0   Object is ready   97m
```

**To Reproduce**
1. Create a clusterdeployment with a beach head service that uses LoadBalancer (I use MSR4). Here is my example:

```
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  finalizers:
  - k0rdent.mirantis.com/cluster-deployment
  labels:
    k0rdent.mirantis.com/component: kcm
  name: vsurzhyk-eu-openstack-cluster-deployment
  namespace: kcm-system
spec:
  config:
    authURL: https://keystone.ic-eu.ssl.mirantis.net/
    bastion:
      enabled: true
      spec:
        flavor: m1.medium
        image:
          filter:
            name: ubuntu-24.04-noble-server-amd64-20240822
        sshKeyName: vsurzhyk
    controlPlane:
      flavor: m1.large
      image:
        filter:
          name: ubuntu-24.04-noble-server-amd64-20240822
      sshPublicKey: vsurzhyk
    controlPlaneNumber: 3
    externalNetwork:
      filter:
        name: public
    identityRef:
      cloudName: openstack
      name: eu-openstack-cloud-config
      region: RegionOne
    worker:
      flavor: m1.large
      image:
        filter:
          name: ubuntu-24.04-noble-server-amd64-20240822
      sshPublicKey: vsurzhyk
    workersNumber: 3
  credential: eu-openstack-cluster-identity-cred
  propagateCredentials: true
  serviceSpec:
    continueOnError: false
    priority: 100
    services:
    - name: postgresql-ha
      namespace: vsurzhyk-msr4
      template: postgresql-ha-15.3.0
      values: |
        persistence:
          enabled: true
          size: 10Gi
          storageClass: csi-cinder-sc-delete
        postgresql:
          password: "support"
          replicaCount: 3
          initdbScripts:
            create_databases.sh: |
              #!/bin/bash
              export PGPASSWORD=$(cat /opt/bitnami/postgresql/secrets/password)
              psql -U postgres -c "CREATE DATABASE harbor_core" && psql -U postgres -c "CREATE DATABASE clair" && psql -U postgres -c "CREATE DATABASE notary_signer" && psql -U postgres -c "CREATE DATABASE notary_server"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
    - name: redis
      namespace: vsurzhyk-msr4
      template: redis-20.11.0
      values: |
        auth:
          password: "support"
        master:
          persistence:
            enabled: true
            size: 8Gi
            storageClass: csi-cinder-sc-delete
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
        replica:
          replicaCount: 3
          persistence:
            enabled: true
            size: 8Gi
            storageClass: csi-cinder-sc-delete
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
    - name: msr4
      namespace: vsurzhyk-msr4
      template: msr-4.0.0
      values: |
        expose:
          type: loadBalancer
        harborAdminPassword: "support"
        persistence:
          enabled: true
          resourcePolicy: "keep"
          persistentVolumeClaim:
            registry:
              storageClass: csi-cinder-sc-delete
              accessMode: ReadWriteOnce
              size: 5Gi
            jobservice:
              jobLog:
                storageClass: csi-cinder-sc-delete
                accessMode: ReadWriteOnce
                size: 5Gi
            trivy:
              storageClass: csi-cinder-sc-delete
              accessMode: ReadWriteOnce
              size: 5Gi
        portal:
          replicas: 2
        core:
          replicas: 2
        jobservice:
          replicas: 1
        registry:
          replicas: 1
        trivy:
          replicas: 2
        database:
          type: external
          external:
            host: "postgresql-ha-pgpool.vsurzhyk-msr4.svc.cluster.local"
            port: "5432"
            coreDatabase: "harbor_core"
            username: "postgres"
            password: "support"
        redis:
          type: external
          external:
            addr: "redis-master.vsurzhyk-msr4.svc.cluster.local:6379"
            sentinelMasterSet: ""
            coreDatabaseIndex: "0"
            jobserviceDatabaseIndex: "1"
            registryDatabaseIndex: "2"
            trivyAdapterIndex: "5"
            username: ""
            password: "support"
    stopOnConflict: false
    syncMode: Continuous
  template: openstack-standalone-cp-0-2-0
status: {}
```

2. Try to delete the clusterdeployment

3. The deletion command is hanging while observing such errors in capo-controller-manager log:

`E0416 10:38:52.841200       1 controller.go:316] "Reconciler error" err="failed to delete router: unable to remove router interface: Expected HTTP response code [200] when accessing [PUT https://neutron.ic-eu.ssl.mirantis.net/v2.0/routers/302e494c-0af4-4e75-b605-1e0bd5ccc942/remove_router_interface], but got 409 instead: {\"NeutronError\": {\"type\": \"RouterInterfaceInUseByFloatingIP\", \"message\": \"Router interface for subnet ad063f6a-b14b-4a5c-9651-a6126090bdca on router 302e494c-0af4-4e75-b605-1e0bd5ccc942 cannot be deleted, as it is required by one or more floating IPs.\", \"detail\": \"\"}}" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="kcm-system/vsurzhyk-eu-openstack-cluster-deployment" namespace="kcm-system" name="vsurzhyk-eu-openstack-cluster-deployment" reconcileID="5999e863-2bf1-4b03-a71d-39b60d58b84d"`

**Expected behavior**
The clusterdeployment is deleted correctly, all the related resources are cleaned up.

**Additional context**
The error is applicable to openstack-standalone-cp-0-1-0 and openstack-standalone-cp-0-2-0 cluster templates
