### ISSUE TITLE
[bug] openstack-standalone-cp-0-2-0 template doesn't upgrade k0s on worker nodes

### ISSUE THREAD

**Issue by ironreality** [k0rdent/kcm#1389]
**Describe the bug**
After changing k0s version in my clusterdeployment's `.spec.k0s.version` - kcm initiates the rolling upgrade for its control plane nodes BUT not for the workers.

**To Reproduce**
1. Create an Openstack clusterdeployment based on openstack-standalone-cp-0-2-0 template with .spec.k0s.version set
2. Change the k0s version (I changed from v1.31.7+k0s.0 to v1.32.3+k0s.0)
3. Observe the rolling upgrade for the control plane nodes but not for the worker nodes. After some time you'll have a mix of k0s versions on your clusterdeployment:

```
$ KUBECONFIG=./kubeconfig kubectl get nodes
NAME                                                      STATUS   ROLES           AGE     VERSION
vsurzhyk-eu-openstack-cluster-deployment-cp-3             Ready    control-plane   26m     v1.32.3+k0s
vsurzhyk-eu-openstack-cluster-deployment-cp-4             Ready    control-plane   19m     v1.32.3+k0s
vsurzhyk-eu-openstack-cluster-deployment-cp-5             Ready    control-plane   17m     v1.32.3+k0s
vsurzhyk-eu-openstack-cluster-deployment-md-blqw6-fzsxw   Ready    <none>          8m38s   v1.31.7+k0s
vsurzhyk-eu-openstack-cluster-deployment-md-blqw6-hclch   Ready    <none>          5m56s   v1.31.7+k0s
vsurzhyk-eu-openstack-cluster-deployment-md-blqw6-sqn84   Ready    <none>          12m     v1.31.7+k0s
```

**Expected behavior**
All the clusterdeployment's nodes are upgraded to the same k0s version.

**Additional context**
Also tried scaling up/down for the worker nodes as a possible work-around but it didn't help as I finished with the mixed k0s versions on my workers.

My clusterdeployment manifest:

```
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  finalizers:
  - k0rdent.mirantis.com/cluster-deployment
  labels:
    k0rdent.mirantis.com/component: kcm
  name: vsurzhyk-eu-openstack-cluster-deployment
  namespace: kcm-system
spec:
  config:
    authURL: https://keystone.ic-eu.ssl.mirantis.net/
    bastion:
      enabled: true
      spec:
        flavor: m1.medium
        image:
          filter:
            name: ubuntu-22.04-x86_64
            #name: ubuntu-24.04-noble-server-amd64-20240822
        sshKeyName: vsurzhyk
    controlPlane:
      flavor: m1.large
      image:
        filter:
          #name: ubuntu-22.04-x86_64
          name: ubuntu-24.04-noble-server-amd64-20240822
      sshPublicKey: vsurzhyk
    controlPlaneNumber: 3
    externalNetwork:
      filter:
        name: public
    identityRef:
      cloudName: openstack
      name: eu-openstack-cloud-config
      region: RegionOne
    worker:
      flavor: m1.large
      image:
        filter:
          name: ubuntu-24.04-noble-server-amd64-20240822
      sshPublicKey: vsurzhyk
    workersNumber: 3
    k0s:
      #version: v1.31.7+k0s.0
      version: v1.32.3+k0s.0
  credential: eu-openstack-cluster-identity-cred
  propagateCredentials: true
  serviceSpec:
    continueOnError: false
    priority: 100
    services:
    - name: postgresql-ha
      namespace: vsurzhyk-msr4
      template: postgresql-ha-15.3.0
      values: |
        persistence:
          enabled: true
          size: 10Gi
          storageClass: csi-cinder-sc-delete
        postgresql:
          password: "support"
          replicaCount: 3
          initdbScripts:
            create_databases.sh: |
              #!/bin/bash
              export PGPASSWORD=$(cat /opt/bitnami/postgresql/secrets/password)
              psql -U postgres -c "CREATE DATABASE harbor_core" && psql -U postgres -c "CREATE DATABASE clair" && psql -U postgres -c "CREATE DATABASE notary_signer" && psql -U postgres -c "CREATE DATABASE notary_server"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
    - name: redis
      namespace: vsurzhyk-msr4
      template: redis-20.11.0
      values: |
        auth:
          password: "support"
        master:
          persistence:
            enabled: true
            size: 8Gi
            storageClass: csi-cinder-sc-delete
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
        replica:
          replicaCount: 3
          persistence:
            enabled: true
            size: 8Gi
            storageClass: csi-cinder-sc-delete
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
    - name: msr4
      namespace: vsurzhyk-msr4
      template: msr-4.0.0
      values: |
        expose:
          type: loadBalancer
        harborAdminPassword: "support"
        persistence:
          enabled: true
          resourcePolicy: "keep"
          persistentVolumeClaim:
            registry:
              storageClass: csi-cinder-sc-delete
              accessMode: ReadWriteOnce
              size: 5Gi
            jobservice:
              jobLog:
                storageClass: csi-cinder-sc-delete
                accessMode: ReadWriteOnce
                size: 5Gi
            trivy:
              storageClass: csi-cinder-sc-delete
              accessMode: ReadWriteOnce
              size: 5Gi
        portal:
          replicas: 2
        core:
          replicas: 2
        jobservice:
          replicas: 1
        registry:
          replicas: 1
        trivy:
          replicas: 2
        database:
          type: external
          external:
            host: "postgresql-ha-pgpool.vsurzhyk-msr4.svc.cluster.local"
            port: "5432"
            coreDatabase: "harbor_core"
            username: "postgres"
            password: "support"
        redis:
          type: external
          external:
            addr: "redis-master.vsurzhyk-msr4.svc.cluster.local:6379"
            sentinelMasterSet: ""
            coreDatabaseIndex: "0"
            jobserviceDatabaseIndex: "1"
            registryDatabaseIndex: "2"
            trivyAdapterIndex: "5"
            username: ""
            password: "support"
    stopOnConflict: false
    syncMode: Continuous
  template: openstack-standalone-cp-0-2-0
status: {}
```
