### ISSUE TITLE
Global variables passtrough

### ISSUE THREAD

**Issue by a13x5** [k0rdent/kcm#1428]
Provide a way to pass global parameters, such as `global.registry` to all templates configuration in the system.
This is needed to provide uniform way to pass registry information across templates in case of using single registry.
Currently the following values should be passed:

```yaml
global:
  registry: "some registry host"
  k0sURL: "some k0s url"
```

The parameters must set using a flags in the controller and there should be a possibility to disable these parameters creation.
