### ISSUE TITLE
[bug] clusterdeployment using invalid credentials hangs indefinitely and cannot be deleted

### ISSUE THREAD

**Issue by quadespresso** [k0rdent/kcm#1483]
**Describe the bug**

When following a basic clusterdeployment example as mentioned at these links:

- https://docs.k0rdent.io/v0.3.0/admin/clusters/deploy-cluster/
- https://docs.k0rdent.io/v0.3.0/quickstarts/quickstart-2-aws/

If one has mistakenly set up bad credentials starting with a secret such as this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-cluster-identity-secret
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
stringData:
  AccessKeyID: "EXAMPLE_ACCESS_KEY_ID"
  SecretAccessKey: "EXAMPLE_SECRET_ACCESS_KEY"
  SessionToken: ""  # empty string here
```

then once getting to the step of deploying the cluster, eg, 

```yaml
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: kubevirt-clusterdeployment
  namespace: kcm-system
spec:
  template: aws-standalone-cp-0-2-1
  credential: aws-cluster-identity-cred
  config:
    clusterLabels: {}
    region: us-east-2
    controlPlane:
      instanceType: t3.small
      rootVolumeSize: 32
    worker:
      instanceType: t3.small
      rootVolumeSize: 32
```

and applying this with `kubectl apply -f <clusterdeployment manifest>`, the manifest seems to be accepted without issue.

Checking on the status of the clusterdeployment:

```bash
❯ kubectl get -n kcm-system clusterdeployments -w
NAME                         READY   SERVICES   TEMPLATE                  MESSAGES                                     AGE
kubevirt-clusterdeployment   False   0/0        aws-standalone-cp-0-2-1   * InfrastructureReady: 0 of 8 completed...   55m
```

Even checking back hours later, the status remains at `0 of 8 completed`. Running `kubectl describe clusterdeployment kubevirt-clusterdeployment -n kcm-system` does not reveal anything helpful in trying to troubleshoot this.

I also discovered that once this clusterdeployment manifest has been applied, if I attempt to correct the underlying issue by updating the secret with the correct manifest (persistent AWS credentials that do not use a session token, thus applying correct values for `AccessKeyID` and `SecretAccessKey` and removing `SessionToken` altogether), this does _not_ unblock the clusterdeployment.

At least as interesting is that this clusterdeployment cannot be deleted. Running `kubectl delete clusterdeployment kubevirt-clusterdeployment -n kcm-system` appears to hang. Interrupting (Ctrl-C) and trying again results in being informed that the deletion is underway. Hours later, the status does not appear to have changed.

There does not appear to be a straightforward way to clean this up. As a tester, my heavy-handed approach is to delete the cluster that hosts KCM, and start fresh.

**To Reproduce**

1. create new credentials; set up new secret that includes `SessionToken` with an empty string, eg,

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-cluster-identity-secret
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
stringData:
  AccessKeyID: "EXAMPLE_ACCESS_KEY_ID"
  SecretAccessKey: "EXAMPLE_SECRET_ACCESS_KEY"
  SessionToken: ""  # empty string here
```

2. continue with the remainder of the credentials setup
3. create clustertemplate manifest that references these new credentials, eg,

```yaml
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: kubevirt-clusterdeployment
  namespace: kcm-system
spec:
  template: aws-standalone-cp-0-2-1
  credential: aws-cluster-identity-cred
  config:
    clusterLabels: {}
    region: us-east-2
    controlPlane:
      instanceType: t3.small
      rootVolumeSize: 32
    worker:
      instanceType: t3.small
      rootVolumeSize: 32
```

4. apply the above clusterdeployment manifest
5. monitor the progress of the clusterdeployment -- wait at least an hour for any progress at all
6. attempt to delete the clusterdeployment (assuming no progress in the above step)

**DISCLAIMER:** I am aware that using short-lived credentials that includes the use of `SessionToken` is not a good practice for a production environment. My efforts were in a test environment. I have since shifted over to using persistent AWS credentials that do not include `SessionToken`.

Also, I have not tested this using something like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-cluster-identity-secret
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/component: "kcm"
type: Opaque
stringData:
  AccessKeyID: "EXAMPLE_ACCESS_KEY_ID"
  SecretAccessKey: "EXAMPLE_SECRET_ACCESS_KEY"
```

where either `AccessKeyID` or `SecretAccessKey` are either corrupt (eg, characters missing, truncated, transposed) or empty, or when a legitimate access/secret key pair has been disabled administratively. I presume I would see the same behaviour as reported in this ticket, but I have not tested this.

**Expected behavior**

At some step in the clusterdeployment, have it attempt a basic validation check of the AWS credentials before attempting to proceed with the clusterdeployment in full. Something akin to the CLI `aws sts get-caller-identity` should be checked, with any exceptions bubbled up to the clusterdeployment status and logs.

For reference, when AWS creds are expired:

```bash
❯ aws sts get-caller-identity

An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired
```

When AWS creds are invalid (random strings for `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`):

```bash
❯ aws sts get-caller-identity

An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
```

When setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to null strings:

```bash
❯ aws sts get-caller-identity

Unable to locate credentials. You can configure credentials by running "aws configure".
```

Additionally, fixing a bad secret should end up updating the credentials that the stalled clusterdeployment can then use to get unblocked.

**Additional context**

n/a
