### ISSUE TITLE
[bug] ClusterDeployment fails with inline IPAMClaim: ClusterIPAM name is empty ("")

### ISSUE THREAD

**Issue by moshiurH** [k0rdent/kcm#1592]
**Describe the bug**
I get a Reconciler error after I add the following IPAM block in Cluster Deployment YAML:
```
  ipamClaim:
    ref: my-vsphere-clusterdeployment1-ipam
    spec:
      provider: in-cluster
      nodeNetwork:
        cidr: 172.16.40.200/29
```

The error message I get in the KCM logs:
```
{"level":"error","ts":"2025-06-02T20:03:55Z","msg":"Reconciler error","controller":"clusterdeployment","controllerGroup":"k0rdent.mirantis.com","controllerKind":"ClusterDeployment","ClusterDeployment":{"name":"my-vsphere-clusterdeployment1","namespace":"kcm-system"},"namespace":"kcm-system","name":"my-vsphere-clusterdeployment1","reconcileID":"cd3bfaff-7927-4864-a49d-8bcf1b791461","error":"failed to process cluster IPAM: failed to fetch ClusterIPAM: ClusterIPAM.k0rdent.mirantis.com \"\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
```

**To Reproduce**
1. Deploy an Openstack VM

![Image](https://github.com/user-attachments/assets/972c82c4-efb7-4007-8a77-471739ab19b4)

2. Install k0rdent in the Openstack VM using kind (`helm install kcm oci://ghcr.io/k0rdent/kcm/charts/kcm --version 1.0.0 -n kcm-system --create-namespace`):
```
root@moshiur-k0rdent-cluster-1:~# kubectl get pods -A
NAMESPACE            NAME                                                           READY   STATUS    RESTARTS        AGE
kcm-system           azureserviceoperator-controller-manager-7cb9b87c94-5h8x4       1/1     Running   0               4m52s
kcm-system           capa-controller-manager-78bdcdc678-kgstm                       1/1     Running   0               4m47s
kcm-system           capd-controller-manager-7586b6577c-c47xk                       1/1     Running   0               4m45s
kcm-system           capg-controller-manager-774958b9b9-5jm9n                       1/1     Running   0               4m42s
kcm-system           capi-controller-manager-5f5558bbf8-pgfzn                       1/1     Running   0               5m49s
kcm-system           capi-ipam-in-cluster-controller-manager-554c4bd487-tvblj       1/1     Running   0               5m20s
kcm-system           capi-ipam-infoblox-controller-manager-6b6fdb5f99-sk6kc         1/1     Running   0               5m17s
kcm-system           capo-controller-manager-f5675885f-mfdmt                        1/1     Running   0               4m35s
kcm-system           capv-controller-manager-ff86b4658-xzm7t                        1/1     Running   0               4m32s
kcm-system           capz-controller-manager-6445f9745-6zkr2                        1/1     Running   0               4m52s
kcm-system           helm-controller-746d7db585-628j6                               1/1     Running   0               8m23s
kcm-system           k0smotron-controller-manager-bootstrap-56cc678b68-8n42r        2/2     Running   0               5m17s
kcm-system           k0smotron-controller-manager-control-plane-5f76869669-z2phj    2/2     Running   0               5m15s
kcm-system           k0smotron-controller-manager-infrastructure-64db98d946-h59ph   2/2     Running   0               4m38s
kcm-system           kcm-cert-manager-6dc4569fb-d7xf9                               1/1     Running   0               8m23s
kcm-system           kcm-cert-manager-cainjector-5598d8c9d5-dnk2f                   1/1     Running   0               8m23s
kcm-system           kcm-cert-manager-webhook-599f9f569b-w9vjj                      1/1     Running   0               8m23s
kcm-system           kcm-cluster-api-operator-7d9cbd5876-6h2dt                      1/1     Running   1 (5m41s ago)   6m29s
kcm-system           kcm-controller-manager-84c4c7d88d-k4h95                        1/1     Running   0               6m29s
kcm-system           kcm-velero-65fdf65985-5xhss                                    1/1     Running   0               8m23s
kcm-system           source-controller-74b597b995-mhq4t                             1/1     Running   0               8m23s
kube-system          coredns-668d6bf9bc-4jfjr                                       1/1     Running   0               106m
kube-system          coredns-668d6bf9bc-cg79q                                       1/1     Running   0               106m
kube-system          etcd-kcm-dev-control-plane                                     1/1     Running   0               106m
kube-system          kindnet-nr5b2                                                  1/1     Running   0               106m
kube-system          kube-apiserver-kcm-dev-control-plane                           1/1     Running   0               106m
kube-system          kube-controller-manager-kcm-dev-control-plane                  1/1     Running   0               106m
kube-system          kube-proxy-6r2qt                                               1/1     Running   0               106m
kube-system          kube-scheduler-kcm-dev-control-plane                           1/1     Running   0               106m
local-path-storage   local-path-provisioner-7dc846544d-b5gws                        1/1     Running   0               106m
orc-system           orc-controller-manager-594d544cd7-7n7wd                        1/1     Running   0               5m43s
projectsveltos       access-manager-bd4f47647-rzlh9                                 1/1     Running   0               5m38s
projectsveltos       addon-controller-77df8ddfc8-p5qcf                              1/1     Running   0               5m38s
projectsveltos       classifier-manager-5dfbd5dc5-qrwj2                             1/1     Running   0               5m38s
projectsveltos       event-manager-5b45494fdd-gppjq                                 1/1     Running   0               5m38s
projectsveltos       hc-manager-7b76cb5fff-s6s96                                    1/1     Running   0               5m38s
projectsveltos       sc-manager-6bbcbc9c9b-zqcqg                                    1/1     Running   0               5m38s
projectsveltos       shard-controller-789b865448-v5754                              1/1     Running   0               5m38s
projectsveltos       sveltos-agent-manager-767b746c76-b8ch8                         1/1     Running   0               4m48s
projectsveltos       techsupport-controller-659df8d9b7-zkh8z                        1/1     Running   0               5m38s
```
3. Craft a yaml to deploy VMs to vSphere environment:
```
root@moshiur-k0rdent-cluster-1:~# cat my-vsphere-clusterdeployment1.yaml
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: my-vsphere-clusterdeployment1
  namespace: kcm-system
spec:
  template: vsphere-standalone-cp-1-0-0
  credential: vsphere-cluster-identity-cred
  config:
    clusterLabels: {}
    controlPlaneNumber: 1
    workersNumber: 1
    vsphere:
      server: 172.16.41.13
      thumbprint: 01:53:C3...
      datacenter: MIRANTIS
      datastore: vmw8-03-bud-ssd
      resourcePool: /MIRANTIS/host/vCluster-2A-Project/Resources/
      folder: /MIRANTIS/vm/2A-Team/moshiur
      username: mhowlader
      password: ${VSPHERE_PASSWORD}
    controlPlaneEndpointIP: 172.16.40.68
    controlPlane:
      ssh:
        user: ubuntu
        publicKey: "ssh-ed25519 AAAAC3NzaC..."
      rootVolumeSize: 50
      cpus: 4
      memory: 4096
      vmTemplate: ubuntu-noble-24.04-cloudimg-moshiur
      network: /MIRANTIS/network/VMWare_VMs_k0s
    worker:
      ssh:
        user: ubuntu
        publicKey: "ssh-ed25519 AAAAC3NzaC..."
      rootVolumeSize: 50
      cpus: 4
      memory: 4096
      vmTemplate: ubuntu-noble-24.04-cloudimg-moshiur
      network: /MIRANTIS/network/VMWare_VMs_k0s
```

4. Confirm the above yaml works:

![Image](https://github.com/user-attachments/assets/f0656609-ed42-407b-8939-d97b2e3e1d0b)

5. Add the IPAM content to the end of the yaml and deploy:
```
root@moshiur-k0rdent-cluster-1:~# cat my-vsphere-clusterdeployment-ipam.yaml
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: my-vsphere-clusterdeployment1
  namespace: kcm-system
spec:
  template: vsphere-standalone-cp-1-0-0
  credential: vsphere-cluster-identity-cred
  config:
    clusterLabels: {}
    controlPlaneNumber: 1
    workersNumber: 1
    vsphere:
      server: 172.16.41.13
      thumbprint: 01:53:C3:...
      datacenter: MIRANTIS
      datastore: vm...ssd
      resourcePool: /MIRANTIS/host/vCluster-2A-Project/Resources/
      folder: /MIRANTIS/vm/2A-Team/moshiur
      username: mh...
      password: ${VSPHERE_PASSWORD}
    controlPlaneEndpointIP: 172.16.40.68
    controlPlane:
      ssh:
        user: ubuntu
        publicKey: "ssh-ed25519 AAAAC..."
      rootVolumeSize: 50
      cpus: 4
      memory: 4096
      vmTemplate: ubuntu-noble-24.04-cloudimg-moshiur
      network: /MIRANTIS/network/VMWare_VMs_k0s
    worker:
      ssh:
        user: ubuntu
        publicKey: "ssh-ed25519 AAAAC3NzaC..."
      rootVolumeSize: 50
      cpus: 4
      memory: 4096
      vmTemplate: ubuntu-noble-24.04-cloudimg-moshiur
      network: /MIRANTIS/network/VMWare_VMs_k0s
  ipamClaim:
    ref: my-vsphere-clusterdeployment1-ipam
    spec:
      provider: in-cluster
      nodeNetwork:
        cidr: 172.16.40.200/29
```

6. Expect the deployment to spin up the VMs but they do not anymore:

![Image](https://github.com/user-attachments/assets/271d036f-28c6-4c80-a9d3-a3e83576d18b)

7. Checking some command outputs:
```
root@moshiur-k0rdent-cluster-1:~# kubectl logs deployment/kcm-controller-manager -n kcm-system --tail=100 | grep my-vsphere-clusterdeployment1
...
{"level":"error","ts":"2025-06-02T18:41:58Z","msg":"Reconciler error","controller":"clusterdeployment","controllerGroup":"k0rdent.mirantis.com","controllerKind":"ClusterDeployment","ClusterDeployment":{"name":"my-vsphere-clusterdeployment1","namespace":"kcm-system"},"namespace":"kcm-system","name":"my-vsphere-clusterdeployment1","reconcileID":"3ee06c9e-c93f-472f-bac6-d8327813adfe","error":"failed to process cluster IPAM: failed to fetch ClusterIPAM: ClusterIPAM.k0rdent.mirantis.com \"\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"}
{"level":"info","ts":"2025-06-02T18:41:58Z","msg":"Reconciling ClusterIPAMClaim","controller":"clusteripamclaim","controllerGroup":"k0rdent.mirantis.com","controllerKind":"ClusterIPAMClaim","ClusterIPAMClaim":{"name":"my-vsphere-clusterdeployment1-ipam","namespace":"kcm-system"},"namespace":"kcm-system","name":"my-vsphere-clusterdeployment1-ipam","reconcileID":"93b77ada-9e93-4610-b6d3-cbed972098f8"}
{"level":"info","ts":"2025-06-02T18:41:58Z","msg":"Creating or updating ClusterIPAM","controller":"clusteripamclaim","controllerGroup":"k0rdent.mirantis.com","controllerKind":"ClusterIPAMClaim","ClusterIPAMClaim":{"name":"my-vsphere-clusterdeployment1-ipam","namespace":"kcm-system"},"namespace":"kcm-system","name":"my-vsphere-clusterdeployment1-ipam","reconcileID":"93b77ada-9e93-4610-b6d3-cbed972098f8"}
{"level":"info","ts":"2025-06-02T18:41:58Z","msg":"Update ClusterIPAMClaim status","controller":"clusteripamclaim","controllerGroup":"k0rdent.mirantis.com","controllerKind":"ClusterIPAMClaim","ClusterIPAMClaim":{"name":"my-vsphere-clusterdeployment1-ipam","namespace":"kcm-system"},"namespace":"kcm-system","name":"my-vsphere-clusterdeployment1-ipam","reconcileID":"93b77ada-9e93-4610-b6d3-cbed972098f8"}
```
and
```
root@moshiur-k0rdent-cluster-1:~# kubectl get clusterdeployment my-vsphere-clusterdeployment1 -n kcm-system -o yaml | yq '.spec.ipamClaim'
ref: my-vsphere-clusterdeployment1-ipam
spec:
  clusterNetwork: {}
  externalNetwork: {}
  nodeNetwork:
    cidr: 172.16.40.200/29
  provider: in-cluster
root@moshiur-k0rdent-cluster-1:~# kubectl get clusteripamclaim my-vsphere-clusterdeployment1-ipam -n kcm-system -o yaml | yq '.status.ipamRef'
null
root@moshiur-k0rdent-cluster-1:~# kubectl get clusteripamclaim -n kcm-system -o yaml
apiVersion: v1
items:
- apiVersion: k0rdent.mirantis.com/v1beta1
  kind: ClusterIPAMClaim
  metadata:
    creationTimestamp: "2025-06-02T19:49:07Z"
    generation: 620
    name: my-vsphere-clusterdeployment1-ipam
    namespace: kcm-system
    ownerReferences:
    - apiVersion: k0rdent.mirantis.com/v1beta1
      kind: ClusterDeployment
      name: my-vsphere-clusterdeployment1
      uid: 01909d5a-b0b1-4c3b-9945-f57d79413aed
    resourceVersion: "2509411"
    uid: e37c690a-026d-4ed0-b22e-490bf5b29250
  spec:
    clusterIPAMRef: my-vsphere-clusterdeployment1-ipam
    clusterNetwork: {}
    externalNetwork: {}
    nodeNetwork:
      cidr: 172.16.40.200/29
    provider: in-cluster
  status:
    bound: true
kind: List
metadata:
  resourceVersion: ""
root@moshiur-k0rdent-cluster-1:~# kubectl get deployment capi-ipam-in-cluster-controller-manager -n kcm-system -o=jsonpath='{.spec.template.spec.containers[*].image}'
registry.k8s.io/capi-ipam-ic/cluster-api-ipam-in-cluster-controller:v1.0.0
```

**Expected behavior**
The vSphere VMs should spin up as before and IPAM should allocate the IPs as expected.

**Additional context**
