### ISSUE TITLE
[enhancement] Add support for 'valuesFiles' in ServiceTemplate 'spec.helm.chartSource' parameters

### ISSUE THREAD

**Issue by dis-xcom** [k0rdent/kcm#1601]
**Is your enhancement / feature request related to a problem? Please describe.**
When working with helm charts for ServiceTemplates, it is possible to specify multiple values files , when helm chart is placed in a HelmRepository, for example:

```
kind: ServiceTemplate
spec:
  helm:
    chartSpec:
...
      sourceRef:
        kind: HelmRepository
        name: ...
      valuesFiles:
      - values.yaml
      - values-common.yaml
...
```

But when helm charts are placed in a git repository, "spec.helm.chartSpec" cannot be used because of issues with GitRepository. The only solution is to use "spec.helm.chartSource".
The problem is that "spec.helm.chartSource" doesn't support "valuesFiles" parameter.

**Describe the solution you'd like**
It would be good to extend "spec.helm.chartSource" in ServiceTemplate, so it could merge valuesFiles for helm charts, like it is done for "spec.helm.chartSpec", for example:

```
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: foo
  namespace: foo-ns
spec:
  helm:
    chartSource:
      remoteSourceSpec:
        git:
          <GitRepository.spec from fluxcd/source-controller/api/v1>
      path: <path-to-chart-in-repo>

      # Example of the new parameter 'valuesFiles' below:
      valuesFiles:
      - values.yaml
      - values-common.yaml
```

**Describe alternatives you've considered**
Make "spec.helm.chartSpec" to work with GitRepository , if there will be any possibility to make it working in future.
