### ISSUE TITLE
[bug] Service upgrade fails

### ISSUE THREAD

**Issue by bak0wski** [k0rdent/kcm#1647]
**Describe the bug**
Following the documentation at [Template Lifecycle Management](https://k0rdent-enterprise-docs-staging.netlify.app/next/reference/template/), the required service upgrade failed with the message that the upgrade was not permitted.

**To Reproduce**
1. Prepare and install a ClusterDeployment
2. Select a ServiceTemplate from the registry that has multiple versions. Example, `ingress-nginx 4.11.3` and `4.11.5`
3. Install each of the ServiceTemplates using Helm
    ```bash
     $ helm install ingress-nginx-4-11-3 oci://ghcr.io/k0rdent/catalog/charts/ingress-nginx-service-template   --version 4.11.3 -n kcm-system
     $ helm install ingress-nginx-4-11-5 oci://ghcr.io/k0rdent/catalog/charts/ingress-nginx-service-template   --version 4.11.5 -n kcm-system
     ```
4. Edit or patch the ClusterDeployment according to the documentation with the lower version-numbered service
    ```yaml
    spec:
       serviceSpec:
         services:
           - template: ingress-nginx-4-11-3  # adjust version as needed, to match the installed ServiceTemplate
             name: ingress-nginx
             namespace: ingress-nginx
             values: |
               ingress-nginx:
                 controller:
                   service:
                     annotations:
                       service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
                   hostPort:
                     enabled: true
    ```
6. Verify the managed cluster has the service
     ``` bash
      # In the managed cluster
      $ kubectl describe pods -n ingress-nginx | grep chart
      helm.sh/chart=ingress-nginx-4.11.3
      ```
8. Write a ServiceTemplateChain manifest following the example in the documentation     ```yaml      spec:
        accessRules:
        - serviceTemplateChains:
          - ingress-nginx-chain
          targetNamespaces:
            list:
            - kcm-system
     ```
8. Update (edit) the AccessManager, again using the example in the documentation
    ```yaml
     spec:
       accessRules:
       - serviceTemplateChains:
         - ingress-nginx-chain
         targetNamespaces:
           list:
           - kcm-system
    ```
8. Upgrade the service:
   1. Apply the newly created ServiceTemplateChain manifest
       ```yaml
        kind: ServiceTemplateChain
        metadata:
          name: ingress-nginx-chain
        spec:
          supportedTemplates:
            - name: ingress-nginx-4-11-5
              availableUpgrades:
              - name: ingress-nginx-4-11-5
               ```        
   2. Edit or Patch the ClusterDeployment to add the new service
       ```yaml
       spec:
          serviceSpec:
            services:
              - template: ingress-nginx-4-11-5  # adjust version as needed, to match the installed ServiceTemplate
                name: ingress-nginx
                namespace: ingress-nginx
                values: |
                  ingress-nginx:
                    controller:
                      service:
                        annotations:
                          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
                      hostPort:
                        enabled: true
       ```
       Patch command
       `kubectl patch clusterdeployment $KCM_CLUSTER_DEPLOYMENT_NAME -n kcm-system --type=merge --patch-file cd-patch-ingress-nginx.yaml`
9. Check the event logs for errors and see
   `service ingress-nginx/ingress-nginx can't be upgraded from ingress-nginx-4-11-3 to ingress-nginx-4-11-5`
    As well, in the ClusterDeployment, the status will show something like:    
    ```yaml
    servicesUpgradePaths:
      - name: ingress-nginx 
      namespace: ingress-nginx
      template: ingress-nginx-4-11-3
      ```

**Expected behavior**
The upgrade is expected to succeed in that the new version of the service is deployed to the managed cluster.

**Additional context**
