### ISSUE TITLE
[bug] CAPO runs with incorrect provider manifest that does not allow metrics collection

### ISSUE THREAD

**Issue by aglarendil** [k0rdent/kcm#1673]
**Describe the bug**
CAPO provider runs with diagnostic address that is not exposed to metrics collectors. It should run on IPADDR_ANY, whilst it in fact runs on localhost, making metrics non-accessible.

**To Reproduce**
1. Run capo provider
2. Create a service monitor to collect metrics
3. Notice that it is down

**Expected behavior**
CAPO provider metrics are collectable.

**Additional Context**
A workaround exists to apply manifests patches like here
https://github.com/pawelzimmer/k0rdent-customizations/blob/main/custom_provider_spec/openstack_infrastructure_provider.yaml#L20
However, it is not a very reliable and "enterprise" thing to do such ad-hoc patches.

**Comment by zerospiel** [comment]
In a normal way, it's done via:

```yaml
# managements.k0rdent.mirantis.com/v1beta1
spec:
  providers:
  - cluster-api-provider-openstack
    config:
      manager:
        metrics:
          bindAddress: <your-endpoint>
```

But CAPO [does not have support](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/v0.12.3/main.go#L113-L172) for the flag (*that is default by any project utilizing the controller-runtime "framework"*) being [set by the CAPI-operator](https://github.com/kubernetes-sigs/cluster-api-operator/blob/v0.20.0/internal/controller/component_customizer.go#L235-L237).

Hence, the only way as of now is to stick to such an ad-hoc approach. This should be done by the CAPO side. k0rdent cannot modify the binary's runtime that runs CAPO.
