### ISSUE TITLE
Replace cloud-nuke with aws-nuke for AWS resource cleanup within CI

### ISSUE THREAD

**Issue by squizzi** [k0rdent/kcm#431]
We use `azure-nuke` for Azure cleanup so we should probably just use `aws-nuke` now since they both use [`libnuke` ](https://github.com/ekristen/libnuke) and share a common filtering system.

**Comment by zerospiel** [comment]
It is not feasable at the moment to share a common filtering system, since AWS does not have an alternative to Azure's `ResourceGroups` (it has but it is not being utilized). So to have something similar for removal one should produce a global (to example) filter similar to the following:

```yaml
accounts:
  '${AWS_ACCOUNT_ID}':
    filters:
      __global__:
      - type: contains
        property: "tag:Name"
        value: "${CLUSTER_NAME}"
        invert: true
      - type: contains
        property: "tag:vpc:Name"
        value: "${CLUSTER_NAME}"
        invert: true
      - type: exact
        property: "tag:kubernetes.io/cluster/${CLUSTER_NAME}"
        value: "owned"
        invert: true
      - type: exact
        property: "tag:sigs.k8s.io/cluster-api-provider-aws/cluster/${CLUSTER_NAME}"
        value: "owned"
        invert: true
      - type: contains
        value: "${CLUSTER_NAME}"
        invert: true
```

There is a catch with it: `aws-nuke` (`libnuke` to be particular) tries to match all the filters until it matches (filters are `OR`-ed) or there are no more filters left, so if a resource won't match for instance one of the filters before inverting (e.g. `Name` does not match the last filter which would be a very common case) then it will match the filter and hence won't be deleted (but should've been!).

So to address this issue there are 2 possible options:
- customize a filter for each of the resources separately — this is definitely not something common
- utilize the `groups` [feature](https://aws-nuke.ekristen.dev/features/filter-groups/), but they are not supposed to work with the `global` filter so that leads to the template `the same 30-40 lines filter for ~100 resources` — this is also not something suitable

So I propose to close the issue at the moment and wait until the `libnuke` will implement a negate expression for the global filter which would solve all the problems
