### ISSUE TITLE
Support to provide e2e testing configuration

### ISSUE THREAD

**Issue by eromanova** [k0rdent/kcm#641]
Currently, there is no straightforward way to provide overrides for our testing configuration. The templates and other configurations are hardcoded. There is a need to test more complex configurations, such as deploying two clusters with different templates on a single management cluster, testing the deployment of the N-1 template, and upgrading to the N template, among others.

Here is an example of testing configuration (it’s a draft. It can be changed/extended):
```
/test-e2e
aws:
  enabled: true
  standalone:
    upgrade: true
    template: aws-standalone-cp-0-0-3
    upgradeTemplate: aws-standalone-cp-0-0-4
  hosted:
    template: aws-hosted-cp-0-0-3
azure:
  enabled: true
  standalone:
    upgrade: true
  hosted:
    upgrade: false
```

If some configuration wasn’t provided it’ll be filled with defaults. Additionally, if the templates for deployment and upgrade are not specified in the configuration, they will be automatically detected. By default, the latest available templates from all the supported in the cluster namespace will be selected and tested.
The configuration will be parsed, encoded in b64, and passed to our Makefile test-e2e target as an env variable.
