### ISSUE TITLE
Validation webhook fails silently for incorrect Management updates

### ISSUE THREAD

**Issue by eromanova** [k0rdent/kcm#721]
I created a custom `ProviderTemplate` and want to enable it by adding it to the `providers` list in the `Management` object. However, when I try to edit the Management object and include my template in the list, the operation fails with the following error:
```
Ekaterina-Romanova-MacBook-Pro-13-inch-M1-2020-:hmc eromanova$ kubectl edit mgmt hmc
error: managements.hmc.mirantis.com "hmc" could not be found on the server
The edits you made on deleted resources have been saved to "/var/folders/tm/k7psfrjn6734hkdlbhjv5xdh0000gn/T/kubectl-edit-2436925435.yaml"
```

I encounter the same issue when trying to add a provider whose `ProviderTemplate` does not exist. However, when I modify the list of existing providers (e.g., removing and re-adding the `cluster-api-provider-vsphere` provider), the operation succeeds without errors.

It seems likely that the `Update` request for the `Management` object is being blocked by a validating webhook. However, no clear error message is provided - neither in the controller logs, nor in the error output.

**UPD:**
The change that I made in the `Management` object was incorrect, I was trying to add the provider and specified the template name under the `name` field while I should have provided the `name` and the `template` fields:
```
providers:
...
- name: ekaz-byo
```

But even when I specified the `template` the `Management` validation failed with:
```
  managements.hmc.mirantis.com "hmc" was not valid:
  * spec.providers: Forbidden: failed to get ProviderTemplate : ProviderTemplate.hmc.mirantis.com "" not found
```

So, there are two issues that should be addressed:
1. Silent webhook failures
2. Management validation webhook should be adapted for BYO templates

**Comment by zerospiel** [comment]
I can't reproduce the issue anymore; perhaps the code has changed since the logic trying to fetch an empty provider during the compatibility checks has changed.

**Comment by halittiryaki** [comment]
also get the same error for custom hetzner provider and cant figure out what the issue is:

status in management object shows
```yaml
providers:
  - name: cluster-api-provider-hetzner
  - ...

cluster-api-provider-hetzner:                                                                                                                                                               
  error: 'Failed to get ProviderTemplate : ProviderTemplate.k0rdent.mirantis.com "" not found'  
```

the provider template is created like:
```yaml
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-hetzner-1-0-6
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: kcm-1-3-1-tpl
    helm.toolkit.fluxcd.io/namespace: kcm-system
    k0rdent.mirantis.com/component: kcm
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-hetzner
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ht-kcm
      version: 0.0.3
```

any ideas what could cause this?
