### ISSUE TITLE
Check promxy autoconfiguration options to automatically collect all servergroups, based on the installed clusters

### ISSUE THREAD

**Issue by gmlexx** [k0rdent/kcm#743]
Currently promxy serverGroups are hardcoded as helm chart values, adding a new cluster requires manual changes.
```
    serverGroups:
      - clusterName: hmc0
        targets:
          - vmauth.hmc0.example.net:443
```
