### ISSUE TITLE
[bug] Incorrect `ManagedCluster` status

### ISSUE THREAD

**Issue by BROngineer** [k0rdent/kcm#813]
**Describe the bug**
The cluster itself is healthy, but the services included in cluster spec and which were expected to be deployed in the cluster are not.

Deployed cluster with a set of services in spec:

```yaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: abortnikov-hmc-managed-01
  namespace: hmc-system
spec:
  template: aws-standalone-cp-0-0-4
  credential: aws-cluster-identity-cred
  services:
    - template: cert-manager-1-16-2
      name: managed-cert-manager
      namespace: cert-manager
    - template: external-secrets-0-11-0
      name: managed-external-secrets
      namespace: external-secrets
```

After a while it became "Ready":

```shell
> k get -nhmc-system managedclusters.hmc.mirantis.com                                                                                                                                                                         ⎈ kind-hmc-dev  16:00:09
NAME                        READY   STATUS
abortnikov-hmc-managed-01   True    ManagedCluster is ready
```

However, this is not true: only one of two services was deployed and due to missing configuration it never entered "ready" state (cert-manager pods continuously restarting due to missing CRDs).
This is reflected in the `.status.services` of the managed cluster, but the conditions are Ok:

```shell
> k get -nhmc-system managedclusters.hmc.mirantis.com abortnikov-hmc-managed-01 -oyaml
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  name: abortnikov-hmc-managed-01
  namespace: hmc-system
...
status:
  conditions:
  ...
  - lastTransitionTime: "2024-12-18T19:38:08Z"
    message: ""
    reason: Succeeded
    status: "True"
    type: SveltosProfileReady
  - lastTransitionTime: "2024-12-18T19:34:54Z"
    message: ""
    reason: Succeeded
    status: "True"
    type: FetchServicesStatusSuccess
  ...
  services:
  - clusterName: abortnikov-hmc-managed-01
    clusterNamespace: hmc-system
    conditions:
    - lastTransitionTime: "2024-12-19T14:00:01Z"
      message: "failed post-install: 1 error occurred:\n\t* job managed-cert-manager-startupapicheck
        failed: BackoffLimitExceeded\n\n"
      reason: Provisioning
      status: "False"
      type: Helm
```

**To Reproduce**
1. Deploy `ManagedCluster` with cert-manager service included. Due to CRDs' installation disabled by default in cert-manager Helm chart the service deployment will fail
2. Wait until cluster becomes "Ready"

**Expected behavior**
It is expected that the `ManagedCluster` state should consider also state of services included to the spec.
