### ISSUE TITLE
Ability to use secrets and cms as helm values in ManagedCluster and MultiClusterService objects

### ISSUE THREAD

**Issue by pbasov** [k0rdent/kcm#817]
In ClusterProfile and Profile objects templateResourceRefs allows templating values from Cluster labels, configmaps and secrets:

https://projectsveltos.github.io/sveltos/template/template_generic_examples/

In this example ManagedCluster we'd like to use secret as a source of values for motel chart:
```
apiVersion: hmc.mirantis.com/v1alpha1
kind: ManagedCluster
metadata:
  labels:
    motel: regional
  name: pbasov-aws-reg0
  namespace: hmc-system
spec:
  config:
...
  services:
  - name: motel-regional
    namespace: motel
    template: motel-regional
    values: |
      victoriametrics:
        vmauth:
          ingress:
            host: vmauth.pbasov-reg-0.project2a-dev.mirantis.com
          credentials:
            username: motel
            password: motel
```
